### PR TITLE
Update Procfile

### PR DESCRIPTION
**Pull request by j-imy**
review needed

### CODE REVIEW

**Comment by vasu-1** [comment]
<table><tbody><tr><td>Thanks for opening the pull request @j-imy! I will look into it ASAP!
 Till then you can improve your code & you can show your love by staring my repos 😋.</td></tr></tbody></table>

**Comment by j-imy** [comment]
test comment

**Comment by vasu-1** [comment]
<br><table><tbody><tr><td>Thanks for closing this pull_request and contributing to our repository @j-imy ! We hope you loved to work with our repository 😋.</td></tr></tbody></table>

**Comment by vasu-1** [comment]
<br><table><tbody><tr><td>Thanks for closing this pull_request and contributing to our repository @j-imy ! We hope you loved to work with our repository 😋.</td></tr></tbody></table>

**Comment by vasu-1** [comment]
<br><table><tbody><tr><td>Thanks for closing this pull_request and contributing to our repository @j-imy ! We hope you loved to work with our repository 😋.</td></tr></tbody></table>

**Comment by j-imy** [comment]
yes

**Comment by vasu-1** [comment]
<br><table><tbody><tr><td>Thanks for closing this pull_request and contributing to our repository @j-imy ! We hope you loved to work with our repository 😋.</td></tr></tbody></table>

**Pull request closed without merging**
