### PR TITLE
Update Procfile

### PR DESCRIPTION
**Pull request by vasu-1**

### CODE REVIEW

**Comment by vasu-1** [comment]
<table><tbody><tr><td>Thanks for opening the pull request @vasu-1! I will look into it ASAP!
 Till then you can improve your code & you can show your love by staring my repos 😋.</td></tr></tbody></table>

**Comment by vasu-1** [comment]
review needed

**Comment by j-imy** [comment]
yes

**Comment by vasu-1** [comment]
<br><table><tbody><tr><td>Thanks for closing this pull_request and contributing to our repository @vasu-1 ! We hope you loved to work with our repository 😋.</td></tr></tbody></table>

**Pull request merged**
